; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_microros_transport = serial
lib_deps = 
	https://github.com/micro-ROS/micro_ros_platformio
	adafruit/Adafruit PWM Servo Driver Library@^3.0.3
	adafruit/Adafruit BusIO@^1.17.4
board_microros_distro = jazzy
monitor_speed = 115200
upload_speed = 115200
monitor_port = /dev/ttyUSB0
build_src_filter = +<main.cpp> -<i2c_scanner.cpp>

[env:i2c_scanner]
platform = espressif32
board = esp32dev
framework = arduino
board_microros_transport = serial
lib_deps = 
	https://github.com/micro-ROS/micro_ros_platformio
	adafruit/Adafruit PWM Servo Driver Library@^3.0.3
	adafruit/Adafruit BusIO@^1.17.4
board_microros_distro = jazzy
monitor_speed = 115200
upload_speed = 115200
build_src_filter = -<main.cpp> +<i2c_scanner.cpp>

[env:servo_calibration]
platform = espressif32
board = esp32dev
framework = arduino
board_microros_transport = serial
lib_deps = 
	adafruit/Adafruit PWM Servo Driver Library@^3.0.3
	adafruit/Adafruit BusIO@^1.17.4
monitor_speed = 115200
upload_speed = 115200
build_src_filter = +<servo_calibration.cpp> -<main.cpp> -<i2c_scanner.cpp>
